server:
  port: 8082
spring:
  application:
    name: gallery-service
  servlet:
    multipart:
      max-request-size: 11MB
      max-file-size: 10MB
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true