version: '3.8'
networks:
  myNetwork:
services:
  zookeeper:
    image: 'bitnami/zookeeper'
    container_name: wibu-zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - myNetwork
  kafka:
    image: 'bitnami/kafka'
    container_name: wibu-kafka
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /opt/data/kafka:/kafka/kafka-logs
    networks:
      - myNetwork
    depends_on:
      - zookeeper
  database:
    container_name: wibu-postgres
    image: postgres
    environment:
      POSTGRES_DB: manga_db
      POSTGRES_USER: hongha
      POSTGRES_PASSWORD: '0705'
    ports:
      - "5432:5432"