environment:
  name: PROD
server:
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://wibu-datasource-dbforlearn.a.aivencloud.com:17672/defaultdb?sslmode=require&&createDatabaseIfNotExist=true
    username: avnadmin
    password: AVNS_7eRNZl-OWS6tAoNVudV
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: bachtran10013@gmail.com
    password: xclu cjlu lzmn toty
    properties:
      mail:
        smtp:
          starttls:
            required: true
  freemarker:
    suffix: ftlh
    template-loader-path: classpath:/templates
logging:
  level:
    org.bachtx.wibuspringboot: DEBUG
  file:
    path: /resource/logs/