spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wibu_database?createDatabaseIfNotExist=true
    username: root
    password: 7522
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
<<<<<<< HEAD
=======
  mail:
    host: smtp.gmail.com
    port: 587
    username: bachtran10013@gmail.com
    password: xclu cjlu lzmn toty
    properties:
      mail:
        smtp:
          starttls:
            required: true
          auth: true
  freemarker:
    suffix: ftlh
    template-loader-path: classpath:/templates
>>>>>>> f2aebd72a660af84175f3f886bd07e267935f275
