server:
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wibu_database?createDatabaseIfNotExist=true
    username: root
    password: 7522
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: bachtran10013@gmail.com
    password: xclu cjlu lzmn toty
    properties:
      mail:
        smtp:
          starttls:
            required: true
  freemarker:
    suffix: ftlh
    template-loader-path: classpath:/templates
logging:
  level:
    org.bachtx.wibuspringboot: DEBUG
  file:
    path: /resource/logs/