security-config:
  token:
    hash-secret: XBYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYHH
    validity: 604800
cloudinary-config:
  cloud-name: dmqacudf0
  api-key: 937729882178114
  api-secret: jyfDIsWPP5W4Fmr70BsN5aN6gas