server:
  port: 8763
spring:
  application:
    name: gateway
  cloud:
    inetutils:
      timeout-seconds: 5
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
  main:
    web-application-type: reactive
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
logging:
  level:
    org:
      springframework:
        web:
          cors:
            reactive:
              DefaultCorsProcessor: debug