server:
  port: 8763
spring:
  application:
    name: gateway
  cloud:
    inetutils:
      timeout-seconds: 5
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-headers: "*"
            allowed-methods: "*"
  main:
    web-application-type: reactive
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway