server:
  port: 8763
spring:
  application:
    name: gateway
  cloud:
    inetutils:
      timeout-seconds: 5
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: manga
          uri: lb://MANGA-SERVICE
          predicates:
            - Path=/manga/**
          filters:
            - StripPrefix=1
        - id: gallery
          uri: lb://GALLERY-SERVICE
          predicates:
            - Path=/gallery/**
          filters:
            - StripPrefix=1
  main:
    web-application-type: reactive
  mvc:
    dispatch-options-request: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
logging:
  level:
    org:
      springframework:
        web:
          cors:
            reactive:
              DefaultCorsProcessor: debug