admin-account:
  email: admin@gmail.com
  username: admin
  password: 123
security-config:
  token:
    hash-secret: 2aZyJmDoedqN3RPshWBlcK8b1vLtH04pXg5MF9VUzEwxnGfS6TQI7OruCkiYAj
    validity: 604800
  password-encoder:
    strength: 10